title: Plant Disease Images Classifier
description: Classify plant disease images using fastai
about:


  This is a Plant Disease Images Classifier using fastai.


  The project was build by Ngoc Pham.


  To try out this mobile app

    - [iOS](https://itunes.apple.com/us/app/food-classifier/id1445356461?ls=1&mt=8)

code: https://github.com/npatta01/web-deep-learning-classifier

sampleImages:
  - name: lasagne
    url: https://upload.wikimedia.org/wikipedia/commons/b/ba/Lasagne_-_stonesoup.jpg
